services:
  mysql:
    image: mysql:8.0
    container_name: mysql-spring-security
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring-security
      MYSQL_USER: marouane
      MYSQL_PASSWORD: Marouane@2001
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - spring-security-net

# Networks
networks:
  spring-security-net: